# Generated by Django 3.2.6 on 2021-08-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0002_own'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Own',
        ),
    ]
