# Generated by Django 3.2.6 on 2021-08-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0005_veg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Soft_drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
