# Generated by Django 3.2.6 on 2021-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0007_auto_20210831_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='veg',
            name='quantity',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
