# Generated by Django 3.2.6 on 2021-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0009_remove_veg_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veg_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('cost', models.IntegerField()),
                ('quantity', models.IntegerField(max_length=3)),
            ],
        ),
    ]
