# Generated by Django 3.2.6 on 2021-09-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0010_veg_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veg_order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
