# Generated by Django 3.2.6 on 2021-09-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0014_veg_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='veg',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
