# Generated by Django 3.2.6 on 2021-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foody', '0015_veg_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veg_order',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='veg_order',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='veg_order',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='veg_order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='veg_order',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
